config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/home', to: 'welcome#home'
  get '/json_sample', to: 'welcome#json_sample'
  get '/fetch_description', to: 'welcome#fetch_description'
  get '/fetch_cars', to: 'cars#fetch_cars'
  get '/fetch_users', to: 'users#fetch_users'
  get '/fetch_user_age', to: 'users#fetch_user_age'
  resources :cars
  resources :users
  resources :books
  resources :games do
    member do
      get 'enroll'
      post 'enrolled_user'
      get 'show_enrolled_user'
    end
      
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :comments, as: :commentable
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :enrollments
  has_many :users, through: :enrollments
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars, dependent: :destroy
  has_one :address, dependent: :destroy
  has_and_belongs_to_many :books
  has_many :enrollments
  has_many :games, through: :enrollments
  

  ## Scope is being used as query builder. ActiveRecord coverts scopes into class methods.0

  scope :adults1, -> { where('age > 18') }
  scope :minor1, -> { where('age < 18') }
  scope :male_members, -> { where(gender: 'male') }
  scope :find_members_of_age, -> age_val { where(age: age_val) if age_val.present?}

  def self.minors
    where('age < 18')
  end

  def self.adults
    where('age > 18')
  end

  def self.female_members
    where(gender: 'female')
  end

  def self.male_adults
    adults1.male_members
  end

  def self.female_adults
    adults.female_members
  end

  def self.find_member_of_age(age_val)
    where(age: age_val) if age_val.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def edit
  end

  def update
    begin  
      if @book.update_attributes(book_params)
        flash[:success] = "#{@book.name} updated successfully."
      else
        flash[:danger] = "Something went wrong."  
      end  
    rescue Exception => e
      flash[:danger] = "something went wrong. Here is the error:#{e.message}"
    end
    redirect_to books_path
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params) 
    if @book.save
      flash[:success] = "Book Added successfully."
    else
      flash[:danger] = "Something went wrong."  
    end
    redirect_to books_path
  end

  def destroy
    if @book.destroy
      flash[:success] = "Book deleted successfully"
    end
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name,:price)
  end

  def set_book
    @book = Book.find_by(id: params[:id])
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    if params[:car_model].present?
      @cars = Car.where(car_model: params[:car_model])
    else  
      @cars = Car.all
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params) 
    if @car.save
      flash[:success] = "Car Added successfully."
      redirect_to cars_path
    end
  end

  def fetch_cars
    c = Car.where(car_model: params[:car_name])
    if c.exists?
      result = { flag: true}
    else
      result = { flag: false}
    end  
    render json: result
  end

private

  def car_params
    params.require(:car).permit(:car_model, :description)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:edit, :update, :destroy, :enroll, :show_enrolled_user]

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:success] = "Game added successfully"
    else
      flash[:danger] = "Something went wrong"
    end
    redirect_to  games_path 
  end

  def edit
  end

  def update
    if @game.update_attributes(game_params)
      flash[:success] = "Game added successfully"
    else
      flash[:danger] = "Something went wrong"
    end
    redirect_to  games_path
  end

  def destroy
    if @game.destroy
      flash[:success] = "Game deleted successfully"
    end
    redirect_to games_path
  end

  def enroll
  end

  def enrolled_user
    @user = User.create(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], gender: params[:gender], email: params[:email])
    @user_enrollment = Enrollment.new(game_id: params[:id], user_id: @user.id, category: params[:category])
    if @user_enrollment.save!
      flash[:success] = "record added successfully"
    end
    redirect_to games_path
  end

  def show_enrolled_user
    @enrolled_users = @game.enrollments
  end

  private

  def set_game
    @game = Game.find_by(id: params[:id])
  end

  def game_params
    params.require(:game).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  def index
    @users = User.all
    @total_user = User.all.count
    @user_male = User.male_members.count
    @user_female = User.female_members.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      flash[:success] = "User Added successfully."
    else
      flash[:danger] = "Something went wrong."  
    end
    redirect_to users_path
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "User Updated successfully."
    else
      flash[:danger] = "Something went wrong."
    end
    redirect_to users_path
  end

  def destroy
    if @user.destroy
      flash[:danger] = "User has been deleted successfully."
      redirect_to users_path
    end
  end

  
  def fetch_users
    u = User.where(email: params[:user_email])
    if u.exists?
      result = { flag: true}
    else
      result = { flag: false}
    end  
    render json: result
  end

  def fetch_user_age
    render json: {age_result: user_age(params[:user_dob].to_date)}
  end  


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :gender, :age, :dob)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_age(dob)
    now = Time.now.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1) 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

  def json_sample
    if params[:myData]
      v = { firstName: 'Niketa'}
    else
      v = {firstName: 'Biswa', lastName: 'Das'}
    end
    render json: v
  end

  def fetch_description
    case params[:car]
    when 'volvo'
      result = { description: 'Description for Volvo'}
    when 'saab'
      result = { description: 'Description for Saab'}
    else
      result = { description: 'No Description'}
    end
    render json: result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def category_options
    [ ["pro", 'pro'], ["semi-pro", 'semi-pro'], ["amature", 'amature'] ]
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def age(dob)
    now = Time.now.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1) 
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/edit.html.haml
.container
  .panel.panel-primary.margin-top-60
    .panel-heading
      %i.fa.fa-book
      Update Book Details
    .panel-body
      = form_for @book, url: book_path(id: @book.id), method: :put do |f|
        .row  
          .form-group.col-lg-6
            %label
              Book name
              %span{style: 'color: red'} *
            = f.text_field :name, placeholder: 'Book name', class: "form-control",required: true
          .form-group.col-lg-6
            %label
              Price
              %span{style: 'color: red'} *
            = f.text_field :price, placeholder: 'Price', class: "form-control",required: true
        .row
          .col-lg-12
            = f.submit "Update Book details", class: "btn btn-primary"           

app/views/books/index.html.haml
.container
  %h3.page-heading
    Book listing
    = link_to new_book_path, class: "btn btn-primary", style: "margin-bottom: 10px; float:right;"  do
      %i.fa.fa-plus
      Add Book
  .table-responsive
    %table.table.table-bordered
      %thead
        %tr.table-head
          %th Book Name
          %th Price
          %th Actions
      %tbody.tbody-bg
        - @books.each do |book|
          %tr
            %td 
              = book.name
            %td 
              = book.price
            %td
              = link_to edit_book_path(id: book.id) do
                %i.fa.fa-edit
              = link_to book_path(id: book.id), method: :delete, data: {confirm: "Are you sure?"} do
                %i.fa.fa-trash  

app/views/books/new.html.haml
.container
  .panel.panel-primary.margin-top-60
    .panel-heading
      %i.fa.fa-book
      Add New Book
    .panel-body
      = form_for @book, url: books_path, method: :post do |f|
        .row
          .form-group.col-lg-6
            %label
              Book Name
              %span{style: 'color: red'} *
            = f.text_field :name, class: "form-control",required: true
          .form-group.col-lg-6
            %label
              Price
              %span{style: 'color: red'} *
            = f.text_field :price, class: "form-control",required: true
        .row
          .col-lg-12
            = f.submit "Add New Book", class: "btn btn-primary"

app/views/cars/index.html.haml
.container
  %h3.page-heading
    Car listing
    = link_to new_car_path, class: "btn btn-primary", style: "margin-bottom: 10px; float:right;"  do
      %i.fa.fa-plus
      Add Car
  .table-responsive
    %table.table.table-bordered
      %thead
        %tr.table-head
          %th Model
          %th Description
      %tbody.tbody-bg
        - @cars.each do |car|
          %tr
            %td 
              = car.car_model
            %td 
              = car.description

app/views/cars/new.html.haml
.container
  .panel.panel-primary.margin-top-60
    .panel-heading
      %i.fa.fa-car
      Add New Car
    .panel-body
      = form_for @car, url: cars_path, method: :post do |f|
        .row
          .form-group.col-lg-6
            %label
              Model
              %span{style: 'color: red'} *
            = f.text_field :car_model, placeholder: 'model', id: "cars", class: "form-control",required: true
            .result-show
          .form-group.col-lg-6
            %label
              Description
              %span{style: 'color: red'} *
            = f.text_field :description, placeholder: 'description', class: "form-control",required: true
            
        .row
          .col-lg-12
            = f.submit "Add New Cars", class: "btn btn-primary", id: "car_submit"
:javascript   
  $(document).ready(function() {
    $('#car_submit').prop('disabled', true);
    $('#cars').keypress(function(){
      var car = $(this).val();
      $.ajax('/fetch_cars', 
      {
        dataType: 'json', // type of response data
        data: { car_name: car},  // data to submit
        timeout: 500,     // timeout milliseconds
        success: function (data,status,xhr) {   // success callback function
          if (data.flag == false) {
            $('.result-show').html('Not exist');
            $('.result-show').css('color', 'green');
            $('#car_submit').prop('disabled', false);
          } else {
            $('.result-show').html('Already exist');
            $('.result-show').css('color', 'red');
            $('#car_submit').prop('disabled', true);
          }
        },
      });
    });

  });         
           

app/views/games/edit.html.haml
.container
  .panel.panel-primary.margin-top-60
    .panel-heading
      %i.fa.fa-gamepad
      Update Game Details
    .panel-body
      = form_for @game, url: game_path(id: @game.id), method: :put do |f|
        .row  
          .form-group.col-lg-6
            %label
              Book name
              %span{style: 'color: red'} *
            = f.text_field :name, placeholder: 'Book name', class: "form-control",required: true
        .row
          .col-lg-12
            = f.submit "Update Game details", class: "btn btn-primary"           

app/views/games/enroll.html.haml
.well
  %h4 User Enrollment form for #{@game.name} 

  = form_tag enrolled_user_game_path(id: @game.id), method: :post do
    .form-group
      %label First Name
      = text_field_tag :first_name, '', class: 'form-control'
    .form-group
      %label Last Name
      = text_field_tag :last_name, '', class: 'form-control'
    .form-group
      %label Age
      = text_field_tag :age, '', class: 'form-control'
    .form-group
      %label Gender
      = text_field_tag :gender, '', class: 'form-control'
    .form-group
      %label Email
      = text_field_tag :email, '', class: 'form-control'
    .form-group
      %label Category
      = select_tag :category, options_for_select(category_options), { prompt: 'Select category' }
  
    .form-group
      = submit_tag "Enroll yourself", class: 'btn btn-danger' 

app/views/games/index.html.haml
.container
  %h3.page-heading
    Game listing
    = link_to new_game_path, class: "btn btn-primary", style: "margin-bottom: 10px; float:right;"  do
      %i.fa.fa-plus
      Add Game
  .table-responsive
    %table.table.table-bordered
      %thead
        %tr.table-head
          %th Game Name
          %th.action-width Actions
      %tbody.tbody-bg
        - @games.each do |game|
          %tr
            %td 
              = game.name
            %td
              = link_to edit_game_path(id: game.id), title: 'Edit' do
                %i.fa.fa-edit
              = link_to game_path(id: game.id), method: :delete, data: {confirm: "Are you sure?"}, title: 'Delete' do
                %i.fa.fa-trash
              = link_to enroll_game_path(id: game.id), title: 'Enroll yourself' do
                %i.fa.fa-pencil
              = link_to show_enrolled_user_game_path(id: game.id), title: 'Show Enrolled User' do
                %i.fa.fa-user-o  
                
                

app/views/games/new.html.haml
.container
  .panel.panel-primary.margin-top-60
    .panel-heading
      %i.fa.fa-gamepad
      Add New Game
    .panel-body
      = form_for @game, url: games_path, method: :post do |f|
        .row
          .form-group.col-lg-6
            %label
              Game Name
              %span{style: 'color: red'} *
            = f.text_field :name, class: "form-control",required: true
        .row
          .col-lg-12
            = f.submit "Add New Game", class: "btn btn-primary"

app/views/games/show_enrolled_user.html.haml
.container
  %h3.page-heading
    Enrolled user for #{@game.name}
  .table-responsive
    %table.table.table-bordered
      %thead
        %tr.table-head
          %th User Name
          %th Category
      %tbody.tbody-bg
        - @enrolled_users.each do |enrollment|
          %tr
            %td 
              = enrollment.user.first_name
            %td
              = enrollment.category  
                
                

app/views/layouts/_flash_messages.html.haml
.container{style: "margin-top: 10px;"}
  - flash.each do |key, value|
    %div{:class => "alert alert-#{key} alert-dismissible"}
      %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
      = value

app/views/layouts/_menu.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      .navbar-brand
        = link_to 'Nik Project', "#"
    %ul.nav.navbar-nav
      %li.active
        = link_to 'Game', games_path
      %li.active
        = link_to 'Book', books_path
      %li.active
        = link_to 'User', users_path 
      %li.active
        = link_to 'Car', cars_path      
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %script{:src => "https://www.gstatic.com/charts/loader.js", :type => "text/javascript"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Practiceapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body 
    #menu
      = render 'layouts/menu'
    = render 'layouts/flash_messages'  
    = yield

app/views/users/_test_bar.html.erb
  <div id="chart_div"></div>
<script type="text/javascript">
  google.charts.load('current', {packages: ['corechart', 'bar']});
  google.charts.setOnLoadCallback(drawBasic);

  function drawBasic() {
    var data = google.visualization.arrayToDataTable([
      ["Name", "Age", { role: "style" } ],
      <% @users.each do |u| %>
        ['<%= u.first_name %>', <%= u.age %>, "#b87333"],
      <% end %>
    ]);

    var options = {
      title: 'Users record with their age',
      chartArea: {width: '100%'},
      hAxis: {
        title: 'User Age',
        minValue: 0
      },
      vAxis: {
        title: 'User Name'
      }
    };

    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));

    chart.draw(data, options);
  }
</script>

app/views/users/edit.html.haml
.container
  .panel.panel-primary.margin-top-60
    .panel-heading
      %i.fa.fa-car
      Update User Details
    .panel-body
      = form_for @user, url: user_path(id: @user.id), method: :put do |f|
        .row
          .form-group.col-lg-6
            %label
              Email
              %span{style: 'color: red'} *
            = f.text_field :email, placeholder: 'email', class: "form-control",required: true
            .email-show  
          .form-group.col-lg-6
            %label
              First Name
              %span{style: 'color: red'} *
            = f.text_field :first_name, placeholder: 'first_name', class: "form-control",required: true
            .result-show
          .form-group.col-lg-6
            %label
              Last Name
              %span{style: 'color: red'} *
            = f.text_field :last_name, placeholder: 'last_name', class: "form-control",required: true
          .form-group.col-lg-6
            %label
              Gender
              %span{style: 'color: red'} *
            = f.radio_button :gender, 'male', :checked => true
            = label :gender_male, 'Male'
            = f.radio_button :gender, 'female'
            = label :gender_female, 'Female'
          .form-group.col-lg-6
            %label
              Date Of Birth
              %span{style: 'color: red'} *
            = f.text_field :dob, placeholder: 'dob', class: "form-control datepicker", required: true
                      
        .row
          .col-lg-12
            = f.submit "Update User", class: "btn btn-primary"
:javascript   
  $(document).ready(function() {
     $('.datepicker').datepicker({
      format: "yyyy/mm/dd",
      autoclose: true,
      todayBtn: "linked"
    });
  });            

app/views/users/index.html.haml
.container
  .jumbotron{style: 'height: auto'}
    .row
      .col-sm-3
        .panel.user-styling
          .panel-heading
            %h1
              %i.fa.fa-users   
          .panel-body
            Users count
            .badge
              = @total_user            
      .col-sm-3
        .panel.user-styling
          .panel-heading
            %h1
              %i.fa.fa-male   
          .panel-body
            Users male count
            .badge
              = @user_male 
      .col-sm-3
        .panel.user-styling
          .panel-heading
            %h1
              %i.fa.fa-female   
          .panel-body
            Users female count
            .badge
              = @user_female
    .row
      .col-sm-4
        #bar-chart-for-users
      .col-sm-4
        #pie-chart-for-users
      .col-sm-4
        = render 'test_bar', locals: {users: @users}

  .jumbotron     
    %h3.page-heading
      User listing
      = link_to new_user_path, class: "btn btn-primary", style: "margin-bottom: 10px; float:right;"  do
        %i.fa.fa-plus
        Add User
    .table-responsive
      %table.table.table-striped.table-bordered
        %thead.thead-light
          %tr.table-head
            %th First Name
            %th Last Name
            %th Gender
            %th Email
            %th Date Of Birth
            %th Action
            %th Age
        %tbody.tbody-bg
          - @users.each do |user|
            %tr
              %td= user.first_name.capitalize
              %td 
                = user.last_name.capitalize
              %td
                = user.gender  
              %td
                = user.email  
              %td= user.dob 

              %td 
                = link_to edit_user_path(id: user.id), class: "btn btn-primary" do
                  %i.fa.fa-user
                  Edit User
                = link_to user_path(id: user.id), data:{confirm: "Are you sure,you want to delete this user?"}, method: :delete, class: "btn btn-primary" do
                  %i.fa.fa-user 
                  Delete   
              %td 
                / = age(user.dob)   
:javascript
  $(document).ready(function() {
    google.charts.load("current", {packages:["corechart"]});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ["Element", "Density", { role: "style" } ],
          ["Total User", #{@total_user.to_i}, "#b87333"],
          ["Male User",  #{@user_male.to_i}, "silver"],
          ["Female User", #{@user_female.to_i}, "gold"],
        ]);

        var view = new google.visualization.DataView(data);
        view.setColumns([0, 1,
                         { calc: "stringify",
                           sourceColumn: 1,
                           type: "string",
                           role: "annotation" },
                         2]);

        var options = {
          title: "Density of Precious Metals, in g/cm^3",
          width: 300,
          height: 200,
          bar: {groupWidth: "95%"},
          legend: { position: "none" },
        };
        var chart = new google.visualization.BarChart(document.getElementById("bar-chart-for-users"));
        chart.draw(view, options);
    }


    google.charts.setOnLoadCallback(drawPie);
    function drawPie() {
      var data = google.visualization.arrayToDataTable([
        ['USERS', 'COUNT'],
        ['MALE',   #{@user_male.to_i}],
        ['FEMALE', #{@user_female.to_i}],
      ]);
      var options = {
        title: 'Users Metrics'
      };
      var chart = new google.visualization.PieChart(document.getElementById("pie-chart-for-users"));
      chart.draw(data, options);
    }
  });
 

app/views/users/new.html.haml
.container
  .panel.panel-primary.margin-top-60
    .panel-heading
      %i.fa.fa-car
      Add New User
    .panel-body
      = form_for @user, url: users_path, method: :post do |f|
        .row
          .form-group.col-lg-6
            %label
              Email
              %span{style: 'color: red'} *
            = f.text_field :email, placeholder: 'email', id: "email", class: "form-control",required: true
            .email-show  
          .form-group.col-lg-6
            %label
              First Name
              %span{style: 'color: red'} *
            = f.text_field :first_name, placeholder: 'first_name', class: "form-control",required: true
            .result-show
          .form-group.col-lg-6
            %label
              Last Name
              %span{style: 'color: red'} *
            = f.text_field :last_name, placeholder: 'last_name', class: "form-control",required: true
          .form-group.col-lg-6
            %label
              Gender
              %span{style: 'color: red'} *
            = f.radio_button :gender, 'male', :checked => true
            = label :gender_male, 'Male'
            = f.radio_button :gender, 'female'
            = label :gender_female, 'Female'
          .form-group.col-lg-6
            %label
              Date Of Birth
              %span{style: 'color: red'} *
            = f.text_field :dob, placeholder: 'dob', class: "form-control datepicker", id: "dob", required: true
            .dob-show         
        .row
          .col-lg-12
            = f.submit "Add New User", class: "btn btn-primary", id: "user_submit"
:javascript   
  $(document).ready(function() {
     $('.datepicker').datepicker({
      format: "yyyy/mm/dd",
      autoclose: true,
      todayBtn: "linked"
    });
    $('#dob').change(function(){
      var udob = $(this).val();
      $.ajax('/fetch_user_age',
      {
        dataType: 'json', // type of response data
        data: { user_dob: udob},  // data to submit
        timeout: 500,     // timeout milliseconds
        success: function (data,status,xhr) {
        if (data.age_result <= 18){
          $('#user_submit').prop('disabled', true);
          $('.dob-show').html('You are Not eligible to create account because of being minor of age' + data.age_result);
          $('.dob-show').css('color', 'red');
        }
        else{
          $('#user_submit').prop('disabled', false);
        }
        }
      });
    });
    $('#user_submit').prop('disabled', true);
    $('#email').change(function(){
      var uemail = $(this).val();
      $.ajax('/fetch_users', 
      {
        dataType: 'json', // type of response data
        data: { user_email: uemail},  // data to submit
        timeout: 500,     // timeout milliseconds
        success: function (data,status,xhr) {   // success callback function
          if (data.flag == false) {
            $('.email-show').html('Not exist');
            $('.email-show').css('color', 'green');
            $('#user_submit').prop('disabled', false);
          } else {
            $('.email-show').html('Already exist');
            $('.email-show').css('color', 'red');
            $('#user_submit').prop('disabled', true);
          }
        },
      });
    });

  });     

app/views/welcome/home.html.haml
%p asgdnagbnv
%select{:name => "cars", id: 'cars'}
  %option{:value => "volvo"} Volvo
  %option{:value => "saab"} Saab
  %option{:value => "fiat"} Fiat
  %option{:value => "audi"} Audi
.result-show
:javascript
  $.ajax('/json_sample', 
  {
    dataType: 'json', // type of response data
    data: { myData: true, param1: 'val' },  // data to submit
    timeout: 500,     // timeout milliseconds
    success: function (data,status,xhr) {   // success callback function
      $('.result-show').append(data.firstName + ' ' + data.lastName);
    },
  });

  $('#cars').change(function(){
    var car = $(this).val();
    $.ajax('/fetch_description', 
    {
      dataType: 'json', // type of response data
      data: { car: car},  // data to submit
      timeout: 500,     // timeout milliseconds
      success: function (data,status,xhr) {   // success callback function
        $('.result-show').html(data.description + ' '+ status);
      },
    });
  });
:css
  .result-show {
    border: 1px solid #ccc;
    height: 100px;
    background: #ccc;
  }